### ISSUE TITLE
Tracking agendas

### ISSUE THREAD

**Issue by locks** [AlexRodwell/netrunner-stream-overlay#11]
Just had a wild idea. Could we track agendas by having our own agenda area in the UI? then we'd programmatically calculate agenda points and threats, and we could show the agendas fanned in the overlay.

**Comment by AlexRodwell** [comment]
I assume that would entail a search feature (that only returns agendas), where you select the scored agenda, and then using the API data, we total/calculate the total agenda points to display, which could override the manually set agenda count?

**Comment by locks** [comment]
Yeah, exactly. This might be tricky for those agendas with conditional points 🤔 we don't want to reimplement game logic, necessarily…

**Comment by AlexRodwell** [comment]
Have thought about this, and the conditional agendas you've mentioned are a really tricky one. I personally think it'd be best to keep this simple, and let either a stream operator or caster to track this manually and update as required, it's not ideal for simplicity, but as you said, re-creating game logic isn't worth the potential technical undertaking, will close this issue for now.
