### ISSUE TITLE
Flipping Sides card display bug

### ISSUE THREAD

**Issue by Chemscribbler** [AlexRodwell/netrunner-stream-overlay#5]
When I flip the player sides the "offscreen" card slide is now the center of the screen
![image](https://github.com/AlexRodwell/netrunner-stream-overlay/assets/21040048/d22b09a8-2e18-4600-86fd-48c67ad414d2)

**Comment by AlexRodwell** [comment]
This looks like an older version from earlier today before I merged my overhaul, could you pull the latest change set and let me know if you have the same issue? I think this was from my WIP commits that caused this to break.

**Comment by Chemscribbler** [comment]
Yup that was the issue
