### ISSUE TITLE
Opacity Adjustment

### ISSUE THREAD

**Issue by Chemscribbler** [AlexRodwell/netrunner-stream-overlay#8]
I think I can probably find how to adjust the opacity in the CSS - but having a slider so people could tweak the color/opacity of the overlay would be a nice QoL feature

**Comment by AlexRodwell** [comment]
Relatively easy to add this option, although a short term solution is to edit the RGBA values in https://github.com/AlexRodwell/netrunner-stream-overlay/blob/main/dashboard/src/lib/components/overlay/MetaSide.svelte#L103-L107 and https://github.com/AlexRodwell/netrunner-stream-overlay/blob/main/dashboard/src/lib/components/overlay/MetaSide.svelte#L127-L131, simply change the `0.8` to whatever opacity you want, i.e. `rgba(0, 0, 0, 0.2)`.

**Comment by AlexRodwell** [comment]
Added this functionality in my last commit.
